### ISSUE TITLE
Add meson.build instructions

### ISSUE THREAD

**Issue by greenmanspirit** [major-lab/json-api-glib#1]
Hello, I am pretty new at both Vala and Meson and I think having some "this is how you add json-api-glib to your meson.build" instructions would be useful for not only myself but any other new users that are trying to learn.

Thanks!

**Comment by arteymix** [comment]
The best way I know is using [wrap-git](http://mesonbuild.com/Wrap-dependency-system-manual.html#branching-subprojects-directly-from-git) to create a dependency. Include a `json-api-glib.wrap` file in a `subprojects` directory:

```
[wrap-git]
directory=json-api-glib
url=https://github.com/major-lab/json-api-glib.git
revision=head
```

Then, in your `meson.build` file, all you need is:

```meson
project('myproject', 'c', 'vala')

glib_dep = dependency('glib-2.0')
gobject_dep = dependency('gobject-2.0')
json_glib_dep = dependency('json-glib-2.0')
json_api_glib_dep = subproject('json-api-glib').get_variable('json_api_glib_dep')

myproject_bin = executable('myproject.vala', 
                           dependencies: [glib_dep, gobject_dep, json_glib_dep, json_api_glib_dep])
```

I just updated the project c509ddf130c1c249e06bfa627bb95302ea4ae8db to make the above example work flawlessly.

It's very possible that you encounter a bug or a missing feature, so don't hesitate to open an issue and I'll try to remedy the situation.

**Comment by greenmanspirit** [comment]
Thank your @arteymix!

**Comment by arteymix** [comment]
No problem!
